extends RefCounted

# Mirrors upstream `MouseMode` enum ordering.
enum {
	MOUSE_REPORTING_NONE,
	MOUSE_REPORTING_NORMAL,
	MOUSE_REPORTING_HILITE,
	MOUSE_REPORTING_BUTTON_MOTION,
	MOUSE_REPORTING_ALL_MOTION,
	MOUSE_REPORTING_FOCUS,
}
